spring:
  application:
    name: hello-spring-boot
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.62.133:3306/mydb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: steven3323237216
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  type-aliases-package: com.johnny.hello.spring.boot.domain
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080
    #  servlet:
    #    context-path: /boot

logging:
  file:
    path: logs/hello-spring-boot
  level:
    org.springframework.web: debug
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
