spring:
  application:
    name: hello-spring-boot

server:
  port: 8080
    #  servlet:
    #    context-path: /boot

logging:
  file:
    path: logs/hello-spring-boot
  level:
    org.springframework.web: debug
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
