spring:
  application:
    name: hello-spring-boot
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8080
    #  servlet:
    #    context-path: /boot

logging:
  file:
    path: logs/hello-spring-boot
  level:
    org.springframework.web: debug
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
